#!/bin/bash
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master

fifo="/tmp/gitbotfifo"

read line
set -- $line

num=$(git log --pretty=oneline ${1}..${2}|wc -l)
branch=${3/refs\/heads\//}
repo=$(basename `pwd`)

echo "7${num} commit(s) pushed to ${repo} on branch '${branch}':" > $fifo
git log --pretty=format:"3%h by %an:  %s%n" ${1}..${2} > $fifo
exit 0
